service: formuljar
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-api-gateway-throttling
  - serverless-plugin-warmup

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3003
  apiGatewayThrottling:
    maxRequestsPerSecond: 200
    maxConcurrentRequests: 50
  warmup:
    prewarm: true
  dev:
    ui_cert: ${opt:ui_cert, "arn:aws:acm:us-east-1:409637905256:certificate/3244fc27-7cce-4a79-b134-7eca6f9a9885"}
    ui_domain:
      - ${opt:ui_domain, "formuljar.maslick.ru"}
    CAPTCHA_PUBLIC: ${env:CAPTCHA_PUBLIC}
    CAPTCHA_SECRET: ${env:CAPTCHA_SECRET}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS}
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
    SHEET_NAME: ${env:SHEET_NAME}
    QUEUE_URL: !Ref FormuljarQueue
  test:
    ui_cert: ${opt:ui_cert, "arn:aws:acm:us-east-1:409637905256:certificate/789b2858-bf9d-4be8-8e33-61a10efbf25e"}
    ui_domain:
      - ${opt:ui_domain, "formuljar-test.maslick.ru"}
    CAPTCHA_PUBLIC: ${env:CAPTCHA_PUBLIC}
    CAPTCHA_SECRET: ${env:CAPTCHA_SECRET}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS}
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
    SHEET_NAME: ${env:SHEET_NAME}
    QUEUE_URL: !Ref FormuljarQueue

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  coreService: formuljar
  accountId: ${opt:account, '409637905256'}
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt:
          - FormuljarQueue
          - Arn
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  environment:
    CAPTCHA_PUBLIC: ${self:custom.${self:provider.stage}.CAPTCHA_PUBLIC}
    CAPTCHA_SECRET: ${self:custom.${self:provider.stage}.CAPTCHA_SECRET}
    TELEGRAM_CHAT_ID: ${self:custom.${self:provider.stage}.TELEGRAM_CHAT_ID}
    TELEGRAM_BOT_TOKEN: ${self:custom.${self:provider.stage}.TELEGRAM_BOT_TOKEN}
    GOOGLE_CREDENTIALS: ${self:custom.${self:provider.stage}.GOOGLE_CREDENTIALS}
    SPREADSHEET_ID: ${self:custom.${self:provider.stage}.SPREADSHEET_ID}
    SHEET_NAME: ${self:custom.${self:provider.stage}.SHEET_NAME}
    QUEUE_URL: ${self:custom.${self:provider.stage}.QUEUE_URL}

functions:
  form:
    handler: handler.form
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /form
          method: post
          cors:
            origin: "*"
    warmup:
      enabled: true

  worker:
    handler: handler.worker
    memorySize: 128
    timeout: 5
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - FormuljarQueue
              - Arn
    warmup:
      enabled: false

resources:
  - ${file(./resources/s3-cf.yml)}
  - ${file(./resources/queue.yml)}