Resources:
  Queue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-sqs-queue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        maxReceiveCount: 1
        deadLetterTargetArn:
          "Fn::GetAtt": [DeadLetterQueue, Arn]
  DeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-sqs-dlq
      MessageRetentionPeriod: 1209600 # 14 days in seconds
